import React, { Profiler } from "react";

import Head from "next/head";

import PostComponent from "../../../components/post/post-comp/PostComponent";
import SinglePostContextProvider from "../../../context/postContexts/SinglePostContext";

function Post() {
  console.log("running post page");
  return (
    <>
      <Head>
        <title>Socialogram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SinglePostContextProvider>
        <PostComponent />
      </SinglePostContextProvider>
    </>
  );
}

export default Post;
