import React, { useContext } from "react";

import Head from "next/head";

import EditProfileComp from "../../../components/profile-accounts/edit-profile/EditProfileComp";
import withAuth from "../../../components/HigherOrderComps/withAuth";

const EditProfilePage = () => {
  return (
    <>
      <Head>
        <title>Socialogram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EditProfileComp />
    </>
  );
};

export default withAuth(EditProfilePage);
