import React, { useEffect } from "react";
import { useContext } from "react";

import Head from "next/head";
import { useRouter } from "next/router";

import ProfileComp from "../../components/profile/ProfileComp";
import withAuth from "../../components/HigherOrderComps/withAuth";
import UserDetailContextProvider from "../../context/userContexts/UserDetaillContext";
import UserPostsContextProvider from "../../context/postContexts/UserPostContext";

function Profile() {
  console.log("running profile page");
  const router = useRouter();
  const { username } = router.query;
  return (
    <>
      <Head>
        <title>Socialogram - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserDetailContextProvider username={username}>
        <UserPostsContextProvider>
          <ProfileComp />
        </UserPostsContextProvider>
      </UserDetailContextProvider>
    </>
  );
}

export default withAuth(Profile);
