import React from "react";

import Head from "next/head";

import ProfileComp from "../../components/profile/ProfileComp";
import UserDetailContextProvider from "../../context/userContexts/UserDetaillContext";

function Saved() {
  return (
    <>
      <Head>
        <title>Socialogram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserDetailContextProvider>
        <ProfileComp />
      </UserDetailContextProvider>
    </>
  );
}

export default Saved;
