import React from "react";

import Head from "next/head";

import LoginComp from "../../components/account-components/Login";
import Footer from "../../components/footer/Footer";

export default function Login() {
  return (
    <>
      <Head>
        <title>Socialogram - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginComp />
      <Footer />
    </>
  );
}
