import React from "react";

import { useRouter } from "next/router";
import Head from "next/head";

import FollowComp from "../../../components/profile/followStatus/FollowComp";
import UserFollowingListContextProvider from "../../../context/userContexts/UserFollowingList";

export default function Followers() {
  const router = useRouter();
  const { username, page } = router.query;
  return (
    <>
      <Head>
        <title>Socialogram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserFollowingListContextProvider>
        <div className="flex justify-center my-40">
          <FollowComp title="following" />
        </div>
      </UserFollowingListContextProvider>
    </>
  );
}
