import React from "react";

import Head from "next/head";

import Navbar from "../../components/navbar/Navbar";
import Footer from "../../components/footer/Footer";
import ProfileComp from "../../components/profile/ProfileComp";

export default function Profile() {
  return (
    <>
      <Head>
        <title>Socialogram - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfileComp />
      <Footer />
    </>
  );
}
