import { useContext, useEffect } from "react";

import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

import HomeComp from "../components/home/Home";

import { authContext } from "../context/AuthContext";
import withAuth from "../components/HigherOrderComps/withAuth";
import Sample from "../components/sample";
import Simple from "../components/simple";
function Home() {
  // console.log("home page running");
  return (
    <>
      <Head>
        <title>Socialogram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Sample /> */}
      <HomeComp />
    </>
  );
}

export default withAuth(Home);
