import { useContext, useEffect } from "react";

import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

import HomeComp from "../components/home/Home";
import UserListContextProvider from "../context/userContexts/UserListContext";
import PostListContextProvider from "../context/postContexts/PostListContext";

import withAuth from "../components/HigherOrderComps/withAuth";

function Home() {
  // console.log("home page running");
  return (
    <>
      <Head>
        <title>Socialogram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserListContextProvider>
        <PostListContextProvider>
          <HomeComp />
        </PostListContextProvider>
      </UserListContextProvider>
    </>
  );
}

export default withAuth(Home);
