import React from "react";

import Head from "next/head";

import SignupComp from "../components/account-components/Signup";
import Footer from "../components/footer/Footer";

export default function Signup() {
  return (
    <>
      <Head>
        <title>Socialogram - Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignupComp />
      <Footer />
    </>
  );
}
